
spring:
  application:
    name: RESTAURANT-SERVICE
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/data/PizzaRestaurantServiceDB;AUTO_SERVER=TRUEe
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

  mvc:
    path match:
      matching-strategy: ant_path_matcher


server:
  port: 8081
  servlet:
    context-path: /api


app:
  pizza-service-url: http://localhost:8081/api/pizzas/restaurant